manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: LykosMidas
      url-base: https://github.dev/LykosMidas
  projects:
    - name: zmk
      remote: LykosMidas
      revision: waveshare_rp2040_zero
      import: app/west.yml
  self:
    path: config
