manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: LykosMidas
      url-base: https://github.com/LykosMidas
  projects:
    - name: zmk-config-taigamepad4
      remote: LykosMidas
      revision: https://github.com/LykosMidas/zmk-config-taigamepad4
      import: app/west.yml
  self:
    path: config
